
function qs(o){var p=new URLSearchParams();Object.keys(o||{}).forEach(function(k){var v=o[k];if(v!==undefined&&v!==null&&v!=="")p.append(k,v)});return p.toString()}
async function api(method,args){try{var q=qs(args||{});var r=await fetch('/api/method/'+method+(q?'?'+q:''),{method:'GET',credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json'}});var j=await r.json();if(j.exc)throw j;return j.message||j}catch(e){console.error(method,e);return null}}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(function(){t.style.display='none'},4200)}
function closeModal(){document.getElementById('modalBack').style.display='none'}
function showModal(title,html){document.getElementById('modalTitle').textContent=title;document.getElementById('modalContent').innerHTML=html;document.getElementById('modalBack').style.display='flex'}
function closeBell(){document.getElementById('bellMenu').classList.remove('open')}
async function doLogout(){try{await fetch('/api/method/logout',{method:'GET',credentials:'same-origin',cache:'no-store'})}catch(e){}window.location.href='/login'}

document.getElementById('sideToggle').onclick=function(){document.getElementById('layout').classList.toggle('side-collapsed')};
document.getElementById('bellBtn').onclick=function(e){e.stopPropagation();document.getElementById('bellMenu').classList.toggle('open');refreshNotifications()};
document.addEventListener('click',function(e){var b=document.getElementById('bellMenu');if(b.classList.contains('open')&&!b.contains(e.target)&&e.target.id!=='bellBtn')closeBell()});
document.getElementById('modalBack').addEventListener('click',function(e){if(e.target.id==='modalBack')closeModal()});

async function refreshStats(){
  var d=await api('restaurant_ops.api.admin_api.get_admin_dashboard_stats');
  if(d&&d.employee_name){document.getElementById('ad-name').textContent=d.employee_name;document.getElementById('ad-welcome').textContent='🏠 نظرة عامة على أداء اليوم — أهلاً '+d.employee_name+' 👋'}
  if(d){document.getElementById('s-comp-open').textContent=d.open_complaints||0;document.getElementById('s-comp-today').textContent=d.today_complaints||0;document.getElementById('s-calls').textContent=d.today_calls||0}
}
async function refreshQueue(){var d=await api('restaurant_ops.api.queue_api.get_queue_status')||{orders:0,complaints:0,total:0};document.getElementById('gq-orders').textContent=d.orders||0;document.getElementById('gq-complaints').textContent=d.complaints||0;document.getElementById('gq-total').textContent=d.total||0;document.getElementById('s-waiting').textContent=d.total||0;var w=document.getElementById('global-queue-widget');if((d.total||0)>0)w.classList.add('alert','shake');else w.classList.remove('alert','shake')}
async function getActiveBreaks(){return await api('restaurant_ops.api.break_api.get_active_breaks')||{active_count:0,overdue_count:0,rows:[]}}
async function refreshBreakCount(){var d=await getActiveBreaks();document.getElementById('s-active-brk').textContent=d.active_count||0;document.getElementById('bellCount').textContent=(d.active_count||0);return d}
async function getExtraRequests(){var m=['restaurant','_ops.api.hr_ops','_api.list_extra_break_requests'].join('');return await api(m,{status:'Pending'})||[]}
async function refreshNotifications(){var br=await refreshBreakCount();var reqs=await getExtraRequests();var total=(br.active_count||0)+(reqs.length||0);document.getElementById('bellCount').textContent=total;var html='';if((br.rows||[]).length){html+=(br.rows||[]).map(function(r){return '<div class="note-item '+(r.overdue?'overdue':'')+'"><b>'+(r.overdue?'⚠️ ':'⏱️ ')+esc(r.employee_name||r.employee)+'</b><div>داخل بريك '+esc(r.break_type)+' من '+esc(r.duration_minutes)+' دقيقة</div>'+(r.overdue?'<div style="color:#b91c1c;font-weight:900">عدى الحد بـ '+esc(r.overdue_minutes)+' دقيقة</div>':'')+'<div class="small">بدأ: '+esc(r.start_time)+'</div><button class="btn red" style="margin-top:7px" onclick="endBreak(\''+esc(r.name)+'\')">إنهاء البريك</button></div>'}).join('')}
if(reqs.length){html+=reqs.map(function(x){return '<div class="note-item"><b>➕ طلب بريك إضافي</b><div>'+esc(x.employee_name||x.employee||'موظف')+'</div><div class="small">راجع HR Ops للموافقة</div><button class="btn blue" style="margin-top:7px" onclick="location.href=\'/hr-ops\'">فتح HR Ops</button></div>'}).join('')}
if(!html)html='<div class="small">لا توجد إشعارات حالياً</div>';document.getElementById('bellBody').innerHTML=html}
async function endBreak(name){if(!confirm('تأكيد إنهاء البريك؟'))return;var r=await api('restaurant_ops.api.break_api.admin_end_break',{break_log:name});if(r&&r.success){toast(r.message||'تم إنهاء البريك');refreshAll()}else toast((r&&r.message)||'فشل إنهاء البريك')}
async function refreshCancels(){var r=await api('restaurant_ops.api.upper_management_email_api.list_order_cancellations')||{count:0,rows:[]};document.getElementById('s-cancels').textContent=r.count||0;document.getElementById('cancelBadge').textContent=r.count||0;return r}
function openCancelForm(){showModal('↩️ تسجيل إلغاء طلب','<div class="form"><div class="field"><label>رقم الطلب *</label><input id="c-order"></div><div class="field"><label>الوردية *</label><select id="c-shift"><option>صباحية</option><option>مسائية</option><option>ليلية</option><option>غير محدد</option></select></div><div class="field"><label>الفرع *</label><input id="c-branch"></div><div class="field"><label>اسم العميل</label><input id="c-customer"></div><div class="field"><label>رقم العميل</label><input id="c-phone"></div><div class="field"><label>سبب الإلغاء *</label><input id="c-reason"></div><div class="field full"><label>ملاحظات</label><textarea id="c-notes" rows="3"></textarea></div></div><div class="actions"><button class="btn green" onclick="saveCancel()">حفظ الإلغاء</button><button class="btn gray" onclick="closeModal()">إغلاق</button></div>')}
async function saveCancel(){var args={order_no:document.getElementById('c-order').value.trim(),shift:document.getElementById('c-shift').value,branch:document.getElementById('c-branch').value.trim(),customer_name:document.getElementById('c-customer').value.trim(),customer_phone:document.getElementById('c-phone').value.trim(),reason:document.getElementById('c-reason').value.trim(),notes:document.getElementById('c-notes').value.trim()};if(!args.order_no||!args.branch||!args.reason){toast('رقم الطلب والفرع وسبب الإلغاء مطلوبين');return}var r=await api('restaurant_ops.api.upper_management_email_api.create_order_cancellation',args);if(r&&r.success){toast('تم تسجيل الإلغاء بنجاح');openCancelReport()}else toast((r&&r.message)||'فشل تسجيل الإلغاء')}
async function openCancelReport(){var r=await refreshCancels();var rows=r.rows||[];var html='<div class="table-wrap">';if(!rows.length)html+='<div style="padding:15px;background:#f8fafc;border-radius:10px;color:#64748b;text-align:center">لا توجد إلغاءات مسجلة اليوم</div>';else html+='<table class="data-table"><thead><tr><th>وقت التسجيل</th><th>رقم الطلب</th><th>الوردية</th><th>الفرع</th><th>العميل</th><th>السبب</th><th>سجلها</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.cancellation_time)+'</td><td>'+esc(r.order_no)+'</td><td>'+esc(r.shift)+'</td><td>'+esc(r.branch)+'</td><td>'+esc(r.customer_name)+'</td><td>'+esc(r.reason)+'</td><td>'+esc(r.logged_by)+'</td></tr>'}).join('')+'</tbody></table>';html+='</div><div class="actions"><button class="btn green" onclick="openCancelForm()">تسجيل إلغاء جديد</button><button class="btn gray" onclick="closeModal()">إغلاق</button></div>';showModal('📄 تقرير الإلغاءات اليوم',html)}
async function refreshAll(){refreshStats();refreshQueue();refreshBreakCount();refreshCancels();}
refreshAll();refreshNotifications();setInterval(refreshStats,8000);setInterval(refreshQueue,3000);setInterval(refreshBreakCount,8000);setInterval(refreshCancels,20000);setInterval(refreshNotifications,15000);
