
let timer=null, baseElapsed=0, basePerf=0, currentBreak=null, employeeSelfClosing=false, alertShown=false;
function api(m,args){args=args||{};let q=new URLSearchParams();Object.keys(args).forEach(k=>{if(args[k]!==undefined&&args[k]!==null)q.append(k,args[k])});return fetch('/api/method/'+m+(q.toString()?'?'+q.toString():''),{method:'GET',credentials:'same-origin',cache:'no-store'}).then(r=>r.json()).then(j=>{if(j.exc)throw j;return j.message||j})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(sec){sec=Math.max(0,parseInt(sec||0));return String(Math.floor(sec/3600)).padStart(2,'0')+':'+String(Math.floor((sec%3600)/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function startTimer(elapsed){baseElapsed=parseInt(elapsed||0);basePerf=performance.now();stopTimer();timer=setInterval(()=>{let s=baseElapsed+Math.floor((performance.now()-basePerf)/1000);let e=document.getElementById('tm');if(e)e.textContent=fmt(s)},1000);let e=document.getElementById('tm');if(e)e.textContent=fmt(baseElapsed)}
function showAdminClosed(a,generic){if(alertShown)return;alertShown=true;stopTimer();a=a||{};currentBreak=a.break_log||currentBreak;document.getElementById('title').textContent='تم إنهاء البريك';document.getElementById('content').innerHTML='<div class="closed-note">تم إنهاء البريك بواسطة الإدارة.<br><span class="muted">اضغط أعلم للعودة للعمل وتحديث الصفحة.</span></div>';document.getElementById('ovAdmin').textContent=a.closed_by||(generic?'الإدارة / النظام':'الإدارة');document.getElementById('ovDetails').innerHTML='نوع البريك: <b>'+esc(a.break_type||'')+'</b><br>وقت الإغلاق: <b>'+esc(a.end_time||'')+'</b><br>مدة البريك: <b>'+esc(a.duration_minutes||'')+' دقيقة</b>'+(generic?'<br><span style="font-size:14px">تم تحديث الحالة من السيرفر لأن البريك لم يعد نشطًا.</span>':'');document.getElementById('adminClosedOverlay').style.display='flex'}
async function pollAdminAlert(){try{let r=await api('restaurant_ops.api.break_api.get_my_break_admin_alert');if(r&&r.has_alert&&r.alert)showAdminClosed(r.alert,false)}catch(e){console.log('alert poll',e)}}
async function pollStateGuard(){if(!currentBreak||alertShown||employeeSelfClosing)return;try{let d=await api('restaurant_ops.api.break_api.get_break_page_data');if(d&&d.success&&!d.active_break){showAdminClosed({message:'تم إنهاء البريك بواسطة الإدارة'},true)}}catch(e){console.log('state guard',e)}}
async function load(){try{let d=await api('restaurant_ops.api.break_api.get_break_page_data');if(!d||!d.success){content.innerHTML='<p>'+(d&&d.message?esc(d.message):'تعذر التحميل')+'</p>';return}title.textContent='أهلاً '+esc(d.employee_name||'')+(d.extension?' — Ext: '+esc(d.extension):'');if(d.active_break){currentBreak=d.active_break.name;content.innerHTML='<p>أنت الآن في بريك: <b>'+esc(d.active_break.break_type||'Break')+'</b></p><div class="timer" id="tm">00:00:00</div><button class="btn end" onclick="endBreak()">إنهاء البريك</button><div class="muted">العداد محسوب من السيرفر ولا يعتمد على ساعة الجهاز.</div>';startTimer(d.active_break.elapsed_seconds||0);return}currentBreak=null;stopTimer();let types=d.break_types||[];content.innerHTML='<div class="grid">'+types.map(t=>'<button class="b" onclick="startBreak(\''+esc(t.name)+'\')"><div style="font-size:40px">⏱️</div><b>'+esc(t.break_type||t.name)+'</b><br>'+esc(t.max_duration_minutes||15)+' دقيقة</button>').join('')+'</div><p class="muted" style="margin-top:15px">اختر نوع البريك للبدء</p>'}catch(e){console.error(e);content.innerHTML='<p>تعذر التحميل</p>'}}
async function startBreak(x){try{let r=await api('restaurant_ops.api.break_api.start_break',{break_type:x});alert((r&&r.message)||'تم');load()}catch(e){alert('تعذر بدء البريك')}}
async function endBreak(){employeeSelfClosing=true;setTimeout(()=>employeeSelfClosing=false,12000);try{let r=await api('restaurant_ops.api.break_api.end_break');alert((r&&r.message)||'تم');currentBreak=null;stopTimer();load()}catch(e){alert('تعذر إنهاء البريك')}}
async function refreshQueue(){try{let d=await api('restaurant_ops.api.queue_api.get_queue_status')||{};qo.textContent=d.orders||0;qc.textContent=d.complaints||0;qt.textContent=d.total||0}catch(e){}}
document.getElementById('ovAck').onclick=function(){let done=()=>location.reload();if(currentBreak){api('restaurant_ops.api.break_api.acknowledge_admin_closed_break',{break_log:currentBreak}).then(done).catch(done)}else done()};
load();refreshQueue();pollAdminAlert();setInterval(refreshQueue,3000);setInterval(pollAdminAlert,2500);setInterval(pollStateGuard,2000);
